### PR TITLE
(freecad) Shim and Code Cleanup

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm @majkinetor @pascalberger @gep13 
## Description

This pull request will fix the issue #1616 and will cleanup the code for the `chocolateyinstall.ps1` file. The `chocolateyinstall.ps1` file currently has blanks for the `url`, `checksum`, and `checksumtype` for 64 bit only builds (mainly the `--pre` package).

## How Has this Been Tested?

Locally tested and with Appveyor

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue 1 link #1616 
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor @gep13 
I know everyone is busy with their life outside of GitHub. This pull Request has been here for 14+ days without any one looking or taking an cursory look. Please, take a look at this PR as it will fix the issue listed plus more minor issues.
Thanks for taking a break from your routine to look. Enjoy your day.

**Comment by majkinetor** [comment]
> This pull Request has been here for 14+ days without any one looking or taking an cursory look

Assuming too much - I took a cursory look on day 0 and I decided cursory look is not enough...

**Comment by RedBaron2** [comment]
@majkinetor 
I'm not really assuming anything, but normally a pull request comes in to the repo for review. The moderators look it over and then request changes or merge it. This PR is simple only changing the shim logic to only make shim for the package executable files, and using tmp files for separate chocolatey install files to clean-up any blank variables for better readability. 
(I really should work on that PR for adding this ability into AU when time allows)
Thanks again for looking at it. I hope that time will allow a moderator to look closer into this PR for review in the future. No, rush just wanted to bump the PR before the bot does it.
Enjoy the weekend.

**Comment by luzpaz** [comment]
bump

**Comment by majkinetor** [comment]
Sorry guys, but activity is low because there are a lot of packages, and still 0 new maintainers.

Chocolatey team also doesn't seem interested in helping making this repository actively maintained. 

As far as I see, until something in that regard changes, this repository is basically very close to unmaintained.

**Review by pauby — APPROVED** [review]
LGTM!

**Comment by RedBaron2** [comment]
@AdmiringWorm @pauby @majkinetor 
I'm going to close this due to it now being outdated due to the massive backlog that this repository has built up.

**Comment by pauby** [comment]
@RedBaron2 Can you explain your comment? There are 3 PR's waiting for merging so I'm assuming you're not referring to that?

**Pull request closed without merging**
