### PR TITLE
(vcredist2010, vcredist2008) Fixed checksums and added update script

### PR DESCRIPTION
**Pull request by jberezanski**
## Description

Fixed checksum after in-place installer update by Microsoft.
Also, for convenience, added a semi-automatic AU script (requires manual update of download id and version).

## How Has this Been Tested?
Manually, in a Windows Server 2019 VM.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
@jberezanski is the intention of this PR to also get vcredist2010 to automatically update when possible?

If so, can you please move the package into the `automatic` directory?

**Comment by jberezanski** [comment]
No, the package will not update automatically (I do not know if it is even possible to obtain the latest download id from anywhere). The script simply automates filling in the url and checksum in chocolateyInstall.ps1, provided you manually set the correct download id and version in update.ps1.

**Comment by jberezanski** [comment]
The same treatment for vcredist2008.

**Review by AdmiringWorm — APPROVED** [review]
LGTM

**Comment by AdmiringWorm** [comment]
@jberezanski your changes have been merged, thanks for your contribution 👍

**Pull request merged**
