### PR TITLE
Add support to PHP 8.0.0

### PR DESCRIPTION
**Pull request by pavinthan**
Add support to PHP 8.0.0

## Description
As PHP 8.0.0 source available add support to PHP 8.0.0

## Motivation and Context
Keep PHP upto date 

## How Has this Been Tested?
Need to test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by RedBaron2** [comment]
@pavinthan 
I believe you are jumping to conclusions about the php package. The php.net website even says that the 8.0 version is a testing version [here](https://www.php.net/archive/2020.php#2020-11-19-1). 
The current package is only stable releases at this time, but feel free to add `--pre` version support via this PR.

FYI: This package is updated via AU scripting that is ran every 4 hours checking the php.net downloads page at that time. It will update if and when 8.0 becomes a stable release candidate.

**Comment by pavinthan** [comment]
@RedBaron2 https://wiki.php.net/todo/php80 

> This package is updated via AU scripting that is ran every 4 hours checking the php.net downloads page at that time. It will update if and when 8.0 becomes a stable release candidate.

I agree and Thanks, I'll wait and close this PR

**Comment by pavinthan** [comment]
@RedBaron2 It's released now and the dependency also need to update It's use vs16

**Comment by RedBaron2** [comment]
@pavinthan 
I have made the issue about the dependency of vs16 being needed for php 8.0 
Feel free to make a PR for this dependency update. When this new  dependency/package is available and the php update.ps1 is edited for it. The php package will auto update to the latest version. Thanks for taking the time to mention this issue.

**Comment by pavinthan** [comment]
Thanks @RedBaron2 I'll close this and create new PR for that, thanks again for your time

**Pull request closed without merging**
