### PR TITLE
Improve julia installer by making it silent

### PR DESCRIPTION
**Pull request by musm**
Make the julia installer silent for a cleaner user experience.

## Description
Silent installation of the julia package

## Motivation and Context
Although this change is not required, it makes the user experience cleaner.
In particular, the julia installer provided by julialang is actually an archive. Therefore it makes sense to first extract the exe archive and then run the msi installer.

Notes: both the 32 and 64 bit downloads extract to the same installer name.
 
Addresses: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1266

### CODE REVIEW

**Comment by musm** [comment]
I would appreciate it if others could test these changes and report back.

**Comment by musm** [comment]
I'll need some help decoding what is wrong with appveyor

**Comment by majkinetor** [comment]
FYI, the error is not visible due to the regression bug in unreleased version of AU this repository uses: https://github.com/majkinetor/au/issues/181.

**Comment by musm** [comment]
can we expect a new release of `au`  soon?

**Comment by majkinetor** [comment]
That is irrelevant for this problem as it can use latest public version (which can't ignore push errors people currently have). I wanted to release already, but waited to see if drastic change I did works as expected, but it turns out it made this problem. I will make this repository use latest official release so you will see the error.

Also, anybody can actually help resolving the error which is better :)

**Comment by musm** [comment]
Great thanks. Indeed:

> Also, anybody can actually help resolving the error which is better :)


👍

**Comment by majkinetor** [comment]
You can try again with some dummy commit here to trigger the build.

df7acecaadd41ea2a57b22e33c819ead086778f4

**Comment by AdmiringWorm** [comment]
Most likely, the cause of the failure is related to the updater can no longer replace with the necessary file paths, due to the change in the install script.

If you look in the update script, I bet it tries to replace the values for `File` and `File64`

**Comment by musm** [comment]
I will fix the issue through julia

**Pull request closed without merging**
