### PR TITLE
fixed url and version generation in update.ps1

### PR DESCRIPTION
**Pull request by SlimyGooblin**
--Resubmitted as previous pull request replaced entire file unnecessarily--
 
It looks like blender's site changed how they name their installers, breaking update.ps1, so I changed the way the url and version number are generated. Hopefully with some added future-proofing.

## Description

Changed the way the variables $re, $url64, and $version64 are created
## Motivation and Context

update.ps1 doesn't currently run, so the blender package will not automatically update

* fixes: Issue #1671

## How Has this Been Tested?

I ran the modified update.ps1 and installed the generated package locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by RedBaron2** [comment]
@SlimyGooblin 
Just a question not that anything is wrong more curiosity.
You find the version with regular expression of `\d\.\d\d\.\d+` , and this is correct. The question is why not something like `\d+\.\d+\.\d+`. The version in the future could change from "0.12.345” to "012.34567.890123”
Just curious, and thanks for looking into this package and making the PR.

**Comment by SlimyGooblin** [comment]
@RedBaron2 
My only reason was that looking through some of blender's past releases, they've never used more than two numbers for minor versions. So I figured this would be a tiny bit "safer" since it could avoid matching the wrong text. Since both work though, changing it shouldn't be a problem if that's preferred.

**Comment by RedBaron2** [comment]
@SlimyGooblin 
Making a "safe" choice is probably the best choice. I'm unaware of any community rule that states that regular expression must be one way or another. @AdmiringWorm or @majkinetor would be the best ones to review the PR. Good work.

**Comment by SlimyGooblin** [comment]
@RedBaron2 
Thanks for the feedback :)

**Comment by pauby** [comment]
Is this still needed? According to the [issue](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1671) this was fixed in this (commit](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1671).

**Comment by SlimyGooblin** [comment]
@pauby
This should no longer be need, I'll close it now.

**Pull request closed without merging**
