### PR TITLE
(freecad) 32/64bit detection and shim logic

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm @majkinetor @pauby @gep13

## Description

This will fix the non-matching versioning between the 32/64bit urls #1635 . This will also fix issue #1616 of no shims with new logic.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue #1616 
  - [x] Issue #1637 
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by adrianinsaval** [comment]
Does this install shims for the installer version too? I think that needs to be done with the Install-Binfile command: https://docs.chocolatey.org/en-us/create/functions/install-binfile

**Comment by RedBaron2** [comment]
@adrianinsaval 
I was unaware of missing shims on the install version. Normally the shims are created so the program can be used from the command or powershell prompt(s).

If you have any further info to share it could be very helpful, thanks.

**Comment by adrianinsaval** [comment]
I couldn't test since the install version is broken but I don't see anything that indicates that a shim would be created in the script, my understanding is that this would install freecad to the default location (C:\Program Files\FreeCAD 0.19) and I think chocolatey doesn't auto generate shims for binaries outside of the lib folder.

On an entirely separate issue, the dev version will apparently no longer be published in the main freecad repo, I'm trying to get a definitive answer of where they will be published going forward, they are currently here: https://github.com/FreeCAD/FreeCAD-AppImage/releases/tag/weekly-builds

**Comment by adrianinsaval** [comment]
@RedBaron2 FreeCAD dev releases will now be published here: https://github.com/FreeCAD/FreeCAD-Bundle/releases/tag/weekly-builds do you think you can change that too in this PR or should I create a new issue for this?

**Comment by RedBaron2** [comment]
@adrianinsaval 
I'll look into changing this in the week. Thanks for letting me know.

**Comment by RedBaron2** [comment]
@adrianinsaval 
I'm just curious now that I got to look closer at the weekly-builds page.  The developers are recommending users switch to the `vc17` version instead of the `vc14`

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor @pauby @pascalberger @gep13 
This PR is updated to also fix the new dev url, and newer regex for `installer-1`, `installer1`, and `installer` files.

This will also update the shim logic.

**Comment by RedBaron2** [comment]
I will close this for now, and start it fresh in a few.

**Pull request closed without merging**
