### PR TITLE
(vcredist2010) Import and update to newest version

### PR DESCRIPTION
**Pull request by jberezanski**
## Description

- imported vcredist2010 from https://github.com/MarkRobertJohnson/ChocolateyPackages
- cleaned up metadata and install script
- fixed reboot handling (https://github.com/MarkRobertJohnson/ChocolateyPackages/pull/16)
- updated to the latest version

## Motivation and Context

The existing package on chocolatey.org started failing because Microsoft removed the (outdated) installers used by that package version.

## How Has this Been Tested?

Manually, in a Windows 10 2004 VM.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/MarkRobertJohnson/ChocolateyPackages)
- [Open Issues](https://github.com/MarkRobertJohnson/ChocolateyPackages/pulls)
  - [x] https://github.com/MarkRobertJohnson/ChocolateyPackages/pull/16
  - [x] https://github.com/MarkRobertJohnson/ChocolateyPackages/pull/18
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed *

### CODE REVIEW

**Comment by RedBaron2** [comment]
@jberezanski 
Just curious to ask if these are the public URL for the files, or are these from someone's account?
The URLs used have the same guid code.

I would hate to have the package be updated and then the URLs don't work because of some cutbacks.

**Comment by jberezanski** [comment]
I got the urls from the Microsoft download page https://www.microsoft.com/en-us/download/details.aspx?id=26999 (projectUrl in nuspec).

**Comment by jberezanski** [comment]
Yes, both x64 and x86 installers are under the same guid on download.microsoft.com - I suppose that is because Microsoft publishes them as one logical package.

**Comment by RedBaron2** [comment]
@jberezanski 
My main reason for asking was could this be converted to be a AU updated script?
It is not necessary, but would be good cause _it could help in troubleshooting in the future._

My 2 cents but LGTM

**Comment by mwallner** [comment]
hey @jberezanski, as I see this package is important for a lot users currently waiting for it, I'm going to merge this PR in so we can move on with the moderation process.

besides that, @RedBaron2 is spot on and it'd be great if this package could converted to a AU package (in a follow-up PR).

**Comment by jberezanski** [comment]
Thanks. Yes, I thought about converting it to AU too, but decided to put it off until later in order to get the fix out as soon as possible with minimum effort.

**Comment by jberezanski** [comment]
I can start working on it right away.

**Pull request merged**
