### PR TITLE
Migrate bind‑toolsonly

### PR DESCRIPTION
**Pull request by ExE-Boss**
## Description

See <https://github.com/AnthonyMastrean/chocolateypackages/issues/392> and <https://github.com/AnthonyMastrean/chocolateypackages/pull/393>.

## Motivation and Context

See <https://github.com/AnthonyMastrean/chocolateypackages/issues/392> and <https://github.com/AnthonyMastrean/chocolateypackages/pull/393>.

## How Has this Been Tested?

Works on my machine™︎.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/AnthonyMastrean/chocolateypackages)
- [Open Issues](https://github.com/AnthonyMastrean/chocolateypackages/issues?q=is:issue+is:open+bind) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [ ] <https://github.com/AnthonyMastrean/chocolateypackages/pull/392>
  - [x] <https://github.com/AnthonyMastrean/chocolateypackages/pull/393>
- [x] *Include the link to the opened PR that removes the package from the original location*: <https://github.com/AnthonyMastrean/chocolateypackages/pull/394> (merged)
- [x] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

---

review?(@zippy1981, @AnthonyMastrean)

### CODE REVIEW

**Comment by RedBaron2** [comment]
@ExE-Boss 
Might I suggest that the version be blanked to `0.0` for merging purposes.
This will allow AU to automatically update the community feed with the latest version when the merge is completed.

**Comment by AdmiringWorm** [comment]
Since this package recently transferred hands to a new maintainer, we can not accept this pull request right now.

We can only accept this package if one of the following criteria have been followed:

1. Explicit permission from the current maintainer (which would be @zippy1981 right now).
2. The package triage process has been followed, and you get added as a maintainer of the package (Triage docs are located here: https://docs.chocolatey.org/en-us/community-repository/users/package-triage-process#package-is-outdated).

As such, until 1 of the above is followed, this pull request will not be reviewed.

**Comment by AdmiringWorm** [comment]
Closing pull request as no explicit permission has been given from the author of the package, and the package triage process has not been followed.

Once either one of these is completed, feel free to open a new pull request to move the package to this repository.

**Comment by PMExtra** [comment]
@ExE-Boss Would you follow up this issue? We need the update urgently, the current version didn't work with the latest Windows 10 anymore.
Notice that I found the latest stable BIND 9 (9.16.16) depends on vcredist 2017 (aka `[14.0,)`) rather than 2012 (aka `[11.0,)`)

**Pull request closed without merging**
