### PR TITLE
Rewrite libreoffice package management

### PR DESCRIPTION
**Pull request by wget**
## Description
Rewrite LibreOffice package management to solve #1342 

## Motivation and Context
* Was relying on website parsing
* URL were fragile and breaking when links weren't under CDN any more
* Hashes were breaking as well
* Gaps were created in version each time fresh stream became still stream. Hack the way AU works in this regard.
* The Document Foundation (TDF) wasn't in control of the workload on their servers. This package is now relying on their update process with a dedicated UserAgent.

## How Has this Been Tested?
Tested several times on my local computer.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by wget** [comment]
Maybe I should replace Write-Host statements by Write-Debug?

**Comment by wget** [comment]
I just really hope AU doesn't come in the way. I don't understand why AppVeyor only tested the version libreoffice-still 6.2.4 and not all of the manual versions I put as streams :/

**Comment by wget** [comment]
As per comment of @majkinetor [left on Gitter](https://gitter.im/chocolatey/chocolatey-coreteampackages?at=5d9f2f3cfcf7602cc565608e) this should work as expected on this repo. We are free to merge at end of day then :)

**Comment by wget** [comment]
Not ready to push yet.
As per discussion with @majkinetor, 1 bug have been found and I would like to fix another warning first (not needed per see but...)

**Comment by wget** [comment]
Please rerun tests of this PR :)

**Comment by majkinetor** [comment]
Just do empty commit.

**Comment by wget** [comment]
(forgot to squash commits first, sorry :/)

**Pull request merged**
