### PR TITLE
Travis CI on Windows: Test choco install mono and python

### PR DESCRIPTION
**Pull request by cclauss**
## Description

Output: https://travis-ci.com/cclauss/chocolatey-coreteampackages

Add a test to ensure that __choco install mono__ and __choco install python__ will work on Travis CI Windows.  https://docs.travis-ci.com/user/reference/windows

We could continue to use AppVeyor to test the repo while we use Travis to test the actual packages in a headless environment.

## Motivation and Context

Travis CI is recommending the use of Chocolatey so we should make sure that core packages run.

This practice would force the creators of Chocolatey packages to document the path to the executables that they install (like __env: PATH="/c/Program Files/Mono/bin:$PATH"__) which is helpful for users who need to manually set $PATH in headless environments like continuous integration and docker.

## How Has this Been Tested?

This is a test.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds ~functionality~ tests)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [ ] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [ ] Issue 1 link
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by cclauss** [comment]
https://github.com/chocolatey/package-verifier/issues/72#issuecomment-492207716

**Comment by majkinetor** [comment]
Seems arbitrary for this repository - why mono/python and not something else.

> This practice would force the creators of Chocolatey packages to document the path to the executables that they install

Here, on this repo, we have a common practice to use `InstallDir` when package has this parameter. `Parameters` section documents this along with any defaults. This is not enforced in any way however, anybody can choose to do this or not (we review this repo but you can't expect that in the wild).

>  who need to manually set $PATH in headless environments like continuous integration and docker.

Its true in majority of cases on this repo that you do not need to do this as relevant packages are put on the PATH or shimmed.

**Comment by cclauss** [comment]
> Its true in majority of cases on this repo that you do not need to do this as relevant packages are put on the PATH or shimmed.

This setting of $PATH does ___not___ work if choco is run on Travis CI which is our use case here.

[johanjanssen/ChocolateyPackages](https://github.com/johanjanssen/ChocolateyPackages/blob/master/.travis.yml) is an example of what I was trying to achieve with this PR.

**Comment by majkinetor** [comment]
If I understand you correctly:

> This setting of $PATH does not work

Have you  tried `Update-SessionEnvironment (refreshenv)` after installing the package. ?

There is nothing specific in mono choco installer - if mono installer adds to PATH (`c/Program Files/Mono/bin`) then choco will too, otherwise choco package can be updated (or upstream issue reported).

**Comment by cclauss** [comment]
We did try running __refreshenv__ on powershell on Travis CI and we found it to be a no-op.

[$Env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User") 
](https://github.com/johanjanssen/ChocolateyPackages/blob/master/.travis.ps1#L5) seems to work.

**Comment by AdmiringWorm** [comment]
> We did try running refreshenv on powershell on Travis CI and we found it to be a no-op.

In that case, it sounds like you ran the edition of `refreshenv` that is meant to be used by cmd. (You need to add some code in the powershell `$PROFILE` script, as it isn't added by choco automatically if that script doesn't already exist, or is empty when choco is installed).

See https://chocolatey.org/docs/troubleshooting#refreshenv-has-no-effect for more information.

**Comment by cclauss** [comment]
Can you please show me an example of how to do that on Travis CI?

**Comment by majkinetor** [comment]
CMD vs Powershell

> refreshenv [.cmd]
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..

> refreshenv [alias Update-SessionEnvironment]
Refreshing environment variables from the registry for powershell.exe. Please wait...

**Comment by cclauss** [comment]
Running [refreshenv.cmd](https://github.com/cclauss/installing-mono-on-Travis-CI-Windows/blob/master/.travis.yml#L15) on Travis CI [does print that output but does not set $PATH](https://travis-ci.com/cclauss/installing-mono-on-Travis-CI-Windows/jobs/202814063#L44).

**Comment by majkinetor** [comment]
Output is always printed and is irrelevant.
What is relevant is weather travis runs in powershell or cmd and how each command is executed (does it spawn new shell or not).

**Comment by cclauss** [comment]
Lots of alternatives tried....
* https://github.com/cclauss/installing-mono-on-Travis-CI-Windows/blob/master/.travis.yml#L10

So far only hardcoded path works.

**Pull request closed without merging**
