### PR TITLE
(vim)Symlink to new version

### PR DESCRIPTION
**Pull request by matsuhav**
Delete old version and turn them into symlinks to new version.

## Description

Overwrite old version's directory with symlink to new version's directory.
When there are already symlinks, relink it.
This example illustrates my aim:
```
**First install
C:\tools\vim\vim80

**Updated to vim81
C:\tools\vim\vim80 -> vim81
C:\tools\vim\vim81

**Updated to vim82
C:\tools\vim\vim80 -> vim82
C:\tools\vim\vim81 -> vim82
C:\tools\vim\vim82
```
## Motivation and Context

Current vim package doesn't delete old version when minor version upgraded.
Vim's minor version has updated recently, and now most users have two versions on their machine.
```
**Current situation
C:\tools\vim\vim81
C:\tools\vim\vim82
```
This is actually my mistake. I overlooked this upgrade scenario when I fixed this package.

This change turns `vim81` into symlink to `vim82` so that we can keep using the old path.
This is very convenient because we don't have to change taskber icon, tile on Start and all other settings which uses vim's path.

In this change, I had to use `mklink` and `rmdir` in `cmd.exe` because `New-Item -ItemType SymbolicLink` fails on test-env and Powershell can't unlink directory symlinks. It will delete link-target directory's
contents too.

## How Has this Been Tested?

I tested in the chocolatey test environment.

Install, upgrade scenario. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [x] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by majkinetor** [comment]
Maybe better solution would be to always update the same folder (and change vim path to just 'vim' without version or 'vim8') ?

**Comment by matsuhav** [comment]
After I saw your comment, I tried the renaming strategy.
And I found that Vim's installer program which is called in `chocolateyinstall.ps1` fails when directory is renamed. The installer requires it is `vim82` and writes it in the registry. We can't rename it.

**Comment by majkinetor** [comment]
> We can't rename it.

Yes we can. There is even a package parameter `InstallDir`.

**Comment by matsuhav** [comment]
`C:\tools` is `$InstallDir` in the first example. Version prefixed directory such as `vim\vim82` is created automatically by unzipping. We can't change this `vim82` name.
```
** After unzip
$InstallDir\vim\_vimrc
$InstallDir\vim\vim82\install.exe
$InstallDir\vim\vim82\vim.exe
$InstallDir\vim\vim82\gvim.exe
...
```
Vim's installer is `$InstallDir\vim\vim82\install.exe`. It creates shortcuts and writes to registry.
It requires it is in `vim82` directory. [This](https://github.com/vim/vim/blob/master/src/dosinst.c#L203) is the error printing line in the source code.
We can't rename `vim82` to `vim` before running `install.exe`, and we can't do it after since all shortcuts already point to `vim82`.

The folder structure I tried was like this.
```
** After unzip and rename
$InstallDir\vim\_vimrc
$InstallDir\vim\vim\install.exe <- Not run!
$InstallDir\vim\vim\vim.exe
$InstallDir\vim\vim\gvim.exe
...
```

**Comment by majkinetor** [comment]
OK, it looks like you have done your homework. Thanks.

**Comment by AdmiringWorm** [comment]
Not really a fan on making symlinks in cases like this, would have preferred that the old directory was moved to the new location instead, and update any shortcuts that had been created in previous versions.

But nonetheless, it is better than leaving shortcuts pointing to the wrong versions.

**Comment by AdmiringWorm** [comment]
@matsuhav your changes have been merged, thanks for your contribution 👍

THese changes will be available when the next version of VIM is released.

**Comment by matsuhav** [comment]
Thank you very much!

**Pull request merged**
