### PR TITLE
Migrate gnupg

### PR DESCRIPTION
**Pull request by wget**
## Description
Like requested [here](https://github.com/chocolatey/chocolatey-coreteampackages/issues/1043#issuecomment-394082932), migrate the package from https://github.com/jtcmedia/chocolatey-packages.

## Motivation and Context
This package is used by a bunch of other package on chocolatey. Also, we will recommend to use this package instead of the old gpg4win versions.

## How Has this Been Tested?
CI system of the jtcmedia (soure from which we migrated from).

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/jtcmedia/chocolatey-packages)
- [PR that removes the package from the original location](https://github.com/jtcmedia/chocolatey-packages/pull/32)
- [x] The [migration guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by wget** [comment]
@AdmiringWorm Should I add a dummy package on gnupg-modern to deprecate the old version?

**Comment by majkinetor** [comment]
* Add `README.md`
* Make it work on AV

**Comment by majkinetor** [comment]
Sup with this ?

**Comment by majkinetor** [comment]
Closing due to no feedback.

**Comment by ExE-Boss** [comment]
I’m attempting this again in #1319 because jtcmedia/chocolatey-packages#32 has already been merged.

**Pull request closed without merging**
