### PR TITLE
vcredist140 14.24.28127.4

### PR DESCRIPTION
**Pull request by ImportTaste**
Microsoft has had a bad habit as of late when it comes to their vcredist download locations, it was a pain to find this outside of automatic updates through Windows Update.

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
We can not update the package to a version that isn't listed anywhere.

There is a requirement for chocolatey packages for being able to verify the binaries being installed is the same as the ones from an official download location (ie, a website).

As this version is only available from windows update (or so it seems anyway, as I have been unable to find it mentioned anywhere else), there is no way to verify that except for doing it through windows update. As such it can not be made available on chocolatey.org yet.

**Comment by AdmiringWorm** [comment]
I will leave this PR open however, until there is a public download location for the version.

**Comment by ImportTaste** [comment]
@AdmiringWorm Did you look at the commit? I put the URLs and checksums for the official binaries in already. You can download them and see for yourself.

**Comment by AdmiringWorm** [comment]
@ImportTaste yes, I did look at the commit.

I also said `download location`, not `download url`.
These two are not the same, the one you are talking about is the `download url`, while the `download location` would be the page a user needs to navigate to to find that download url.

**Comment by ImportTaste** [comment]
I see. Well, I think it would be a good idea to at least make it a prerelease package. Microsoft has been known to not be the most organized in regards to the vcredist binaries. They leave so many outdated versions up that are top results on Google, and sometimes the most up-to-date versions are quite hard to find, like vcredist2013's being hidden away on a [support page](https://support.microsoft.com/en-us/help/3138367/update-for-visual-c-2013-and-visual-c-redistributable-package) that isn't even linked to anywhere else on their website.

But if you don't want to do that, no big deal, I won't press further.

**Comment by AdmiringWorm** [comment]
> I see. Well, I think it would be a good idea to at least make it a prerelease package.

Even if publishing it as a pre-release, it would still be the same problem when it comes to moderation (sure, it skips human moderation, but so do every package in this repo. Which is why we need to follow the guidelines before we merge anything in).

> But if you don't want to do that, no big deal, I won't press further.

While I would love to, it can't (as I said earlier) happen until there is a page we can browse to grab the link.

**Comment by AdmiringWorm** [comment]
I noticed today that the package have been updated to the version you wanted to add in this PR.

So apparently MS have figured out their mistake, and finally provided the latest version on the page we parse.

As such this PR is no longer needed, I do appreciate you trying to help out though. 😃

**Pull request closed without merging**
