### PR TITLE
Updated packages icon

### PR DESCRIPTION
**Pull request by xmha97**
Updated WPS (KingSoft) office icon (New Brand icon)
Updated Spotify icon (using SVG file)
Updated Tor-Browser icon (using SVG file)

### CODE REVIEW

**Comment by pauby** [comment]
What's the purpose behind changing the Spotify and Tor-Browser icons to SVG?

Submitting the Kingsoft image by itself is not going to work. The [.nupsec](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/kingsoft-office-free/kingsoft-office-free.nuspec#L11) uses an icon which is hosted by rawgit.com (which is no longer operating) and refers to a specific commit.

**Comment by xmha97** [comment]
> 
> 
> What's the purpose behind changing the Spotify and Tor-Browser icons to SVG?
> 
> Submitting the Kingsoft image by itself is not going to work. The [.nupsec](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/kingsoft-office-free/kingsoft-office-free.nuspec#L11) uses an icon which is hosted by rawgit.com (which is no longer operating) and refers to a specific commit.

Because in SVG images we do not face the problem of quality reduction.

**Comment by pauby** [comment]
> Because in SVG images we do not face the problem of quality reduction.

Can you point me to where you are seeing a reduced quality image? The package pages look fine _to me_.

The [PNG format for package icons is the preferred format](https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines).

**Comment by xmha97** [comment]
> 
> 
> > Because in SVG images we do not face the problem of quality reduction.
> 
> Can you point me to where you are seeing a reduced quality image? The package pages look fine _to me_.
> 
> The [PNG format for package icons is the preferred format](https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines).

OK, I close this PR.

**Pull request closed without merging**
