### PR TITLE
(libreoffice-fresh) Patch to fix the 404 error

### PR DESCRIPTION
**Pull request by RedBaron2**
@AdmiringWorm @majkinetor @gep13 @wget 

Patch to fix the 404 error that was blocking the updates

## Description

This will unblock the stream from updating. Due to a poorly formed url string the `6.4.7` version was having a 404 error. This due to the _**"hacking the way AU streams are working here"**_ was causing a failure to update the package

## Motivation and Context

This is mentioned in issue #1526 

## How Has this Been Tested?

Locally and via appveyor [here](https://ci.appveyor.com/project/RBZ/development/builds/35680703)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](add_link_to_original_repository_location)
- [Open Issues](link_to_the_generic_location_of_open_issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [x] Issue 1 #1526 
  - [ ] Issue 2 Link
- [ ] *Include the link to the opened PR that removes the package from the original location*
- [ ] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor 
I think the testing script needs a cookie or some tweaking
`  A single stream must be included when forcing package update (9.26s)`

**Comment by RedBaron2** [comment]
@AdmiringWorm @majkinetor @wget 
This package using "**hacking the way AU streams are working**" is really messing with the PR Testing script. Even changing the `json` file to be only one update version didn't solve the testing script name being passed to AU.
My [test](https://ci.appveyor.com/project/RBZ/development/builds/35680703) shows its works and even the error file inside the artifact [au_temp.7z](https://ci.appveyor.com/api/buildjobs/w1xbdbnip2hl265o/artifacts/au_temp.7z) the write-host lines of `libreoffice-streams - checking updates using au version 2020.10.14.171228
url -https://downloadarchive.documentfoundation.org/libreoffice/old/6.3.6.2/win/x86_64/LibreOffice_6.3.6.2_Win_x64.msi.sha256-
url -https://downloadarchive.documentfoundation.org/libreoffice/old/6.3.6.2/win/x86/LibreOffice_6.3.6.2_Win_x86.msi.sha256-`

Please, manually check it again when you have time.

**Comment by wget** [comment]
I asked the TDF team to check out and it seems the problem was due to their TDF update service. The fix they provided from their side is fixing this problem IMHO.

6.4.7 doesn't exist :)

**Comment by RedBaron2** [comment]
@wget 
I have to disagree about version `6.4.7` it does exist.
`https://downloadarchive.documentfoundation.org/libreoffice/old/6.4.7.2/win/x86/LibreOffice_6.4.7.2_Win_x86.msi`
--or--
`https://downloadarchive.documentfoundation.org/libreoffice/old/6.4.7.2/win/x86_64/LibreOffice_6.4.7.2_Win_x64.msi`

I still think that the helper script needs to have checks in place for possible (Ex: url (404) errors) that may pop-up. This might be in addition to the proxy issue #1515 
I'm glad that you where able to get your script to work. 👍 

I will close this due to the package being currently up to date.

**Comment by wget** [comment]
Sure it exists but it is not reported as existing by the update service ;) That's why there is no check there.

We are relying on the version provided by the update service. The latter is authoritative **not** the files being on the server :)

**Pull request closed without merging**
