### PR TITLE
(docker-kitematic) Deprecate Kitematic package

### PR DESCRIPTION
**Pull request by abejenaru**
## Description
Kitematic has been deprecated and is no longer in active development.
I am deprecating this package and redirecting it to docker-desktop.

## Motivation and Context
Kitematic has been deprecated and is no longer in active development.

## How Has this Been Tested?
Not tested, only .nuspec update.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:
- [x] My code follows the code style of this repository.
- [x] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Review by AdmiringWorm — CHANGES_REQUESTED** [review]
Since the package is deprecated, can you please move the `docker-kitematic` folder into the `deprecated` folder?

**Comment by abejenaru** [comment]
> Since the package is deprecated, can you please move the `docker-kitematic` folder into the `deprecated` folder?

No problem, it's done!

**Comment by pauby** [comment]
Is Kitematic (the product) being deprecated in favour of Docker Desktop (the product) by Docker themselves or just EOL'd.?

**Review by pauby — APPROVED** [review]

**Comment by pauby** [comment]
LGTM. Thanks @abejenaru!

**Pull request merged**
