### PR TITLE
Deprecate `gnupg‑modern`

### PR DESCRIPTION
**Pull request by ExE-Boss**
## Description
This creates a deprecated stub-package for #1333 according to https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package.

## Motivation and Context
Because @gep13 wouldn’t approve [gnupg](https://chocolatey.org/packages/gnupg) until after [gnupg‑modern](https://chocolatey.org/packages/gnupg-modern) was deprecated.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/jtcmedia/chocolatey-packages)
- [Open Issues](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues) *Add the different issues underneath, and tick those that are fixed in this PR*
  - [ ] #1333
- [x] https://github.com/jtcmedia/chocolatey-packages/pull/32
- [x] The [migration guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

---

review?(@gep13, @jtcmedia,@majkinetor, @wget)

### CODE REVIEW

**Comment by gep13** [comment]
@ExE-Boss thank you for taking the time to do this, I appreciate it.

I have added the `chocolatey` user as a maintainer of this package on chocolatey.org.

**Comment by gep13** [comment]
To quote what I heard from someone recently...

@majkinetor said...
Wow, A-mazing.

**Comment by majkinetor** [comment]
And, how does that feel ?

**Comment by gep13** [comment]
>@majkinetor said...
And, how does that feel ?

In all honesty, I am not phased by it anymore, if anything, I expected something like this.  I have been down this road with you before trying to get things done, and in all honesty, I am not bothered by it anymore, life is too short.  I feel for @ExE-Boss who has gone to the trouble to do the work and create this PR though.

The really interesting thing is, if the process for moving this package to the Core Team Repository had been followed properly we wouldn't even be having this conversation.  

During that process, the id of the package was changed, thus causing the duplicate package id, and that is the problem.  A PR was been sent to @jtcmedia repository to remove the package (and yes, it's a git repository so it can be retrieved, but that isn't the point) from that repository to move it here.  If this is where the package is going to reside in its new state then I believe a deprecated package in this repository with the old name makes a lot of sense.  

If you aren't going to allow this in so that we can put this matter to bed then I would suggest that the correct course of action would be to create another PR to @jtcmedia repository to re-instate the package and we can reject the new `gnupg` package.

**Comment by majkinetor** [comment]
> In all honesty, I am not phased by it anymore, if anything, I expected something like this.

Thats great, we are getting to know and "tolerate" each other. 

> If you aren't going to allow this in so that we can put this matter to bed then I would suggest that the correct course of action would be to create another PR to @jtcmedia repository to re-instate the package and we can reject the new gnupg package.

That would make me behave like you. 👿 

I choose to be maker and enabler, not a showstopper.

**Pull request merged**
