### PR TITLE
[PHP] Revert dependency for PHP 8.0.0 to vcredist140

### LINKED ISSUE #1587: (php) Revert dependency change for PHP
PHP 8.0 does not require `visualstudio2019buildtools` for installing it and should work fine with `vcredist140`.
`vcredist140` supports Visual studio 2015 to 2019, i.e. it covers `vs16`.

`visualstudio2019buildtools` is required for building PHP from source, not for installing PHP.

## Expected Behavior
Installing PHP 8.0.0 should install `vcredist140` just like it did with previous versions of PHP.

## Current Behavior
After #1585, Installing PHP 8.0.0 installs `visualstudio2019buildtools` as a dependency.

## Possible Solution
in `automatic/php/update.ps1`
```diff
- 'vs16' = @{ Id = 'visualstudio2019buildtools'; Version = '16.8.2.0' }
+ 'vs16' = @{ Id = 'vcredist140'; Version = '14.28.29325.2' }
```

## Steps to Reproduce (for bugs)
1. Installing `PHP 8.0.0` installs `visualstudio2019buildtools`, which is not required.

## Your Environment

* Package Version used: `PHP (Hypertext Preprocessor) 8.0.0`
* Operating System and version: `Windows 10`
* Chocolatey version: `0.10.16-beta`
* Install/uninstall gist: `choco install php`

### PR DESCRIPTION
**Pull request by shivammathur**
This PR reverts the dependency change for PHP in #1585 from `visualstudio2019buildtools` to `vcredist140`.
This fixes #1587. 

## Description
`visualstudio2019buildtools` is not required for installing PHP runtime. `vcredist140`, which was being used for previous versions of PHP is sufficient and correct dependency for PHP 8.0.0.

## Motivation and Context
- `visualstudio2019buildtools` is not the correct dependency for PHP 8.0.0 while `vcredist140` is.
- This issue is also a blocker for installing PHP 8.0.0 on GitHub Actions/Azure windows environments as `visualstudio2019buildtools` conflicts with their VS setup. actions/virtual-environments#2170

## How Has this Been Tested?
Tested on clean `mcr.microsoft.com/windows/servercore:ltsc2019` and `mcr.microsoft.com/windows:2004` docker images.

If you see near the end of logs, php does not work until `vcredist140` is installed.
<details><summary>Testing Logs</summary>
<p>

```cmd
C:\>@"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass
-Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadStri
ng('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
Getting latest version of the Chocolatey package for download.
Getting Chocolatey from https://chocolatey.org/api/v2/package/chocolatey/0.10.15.
Downloading 7-Zip commandline tool prior to extraction.
Extracting C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocInstall\chocolatey.zip to C:\Users\Containe
rAdministrator\AppData\Local\Temp\chocolatey\chocInstall...
Installing chocolatey on this machine
Creating ChocolateyInstall as an environment variable (targeting 'Machine')
  Setting ChocolateyInstall to 'C:\ProgramData\chocolatey'
WARNING: It's very likely you will need to close and reopen your shell
  before you can use choco.
Restricting write permissions to Administrators
We are setting up the Chocolatey package repository.
The packages themselves go to 'C:\ProgramData\chocolatey\lib'
  (i.e. C:\ProgramData\chocolatey\lib\yourPackageName).
A shim file for the command line goes to 'C:\ProgramData\chocolatey\bin'
  and points to an executable in 'C:\ProgramData\chocolatey\lib\yourPackageName'.

Creating Chocolatey folders if they do not already exist.

WARNING: You can safely ignore errors related to missing log files when
  upgrading from a version of Chocolatey less than 0.9.9.
  'Batch file could not be found' is also safe to ignore.
  'The system cannot find the file specified' - also safe.
chocolatey.nupkg file not installed in lib.
 Attempting to locate it from bootstrapper.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
WARNING: Not setting tab completion: Profile file does not exist at
'C:\Users\ContainerAdministrator\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'.
Chocolatey (choco.exe) is now ready.
You can call choco from anywhere, command line or powershell by typing choco.
Run choco /? for a list of functions.
You may need to shut down and restart powershell and/or consoles
 first prior to using choco.
Ensuring chocolatey commands are on the path
Ensuring chocolatey.nupkg is in the lib folder

C:\>choco install php
Chocolatey v0.10.15
Installing the following packages:
php
By installing you accept licenses for the packages.
Progress: Downloading visualstudio2019buildtools 16.8.2.0... 100%
Progress: Downloading chocolatey-visualstudio.extension 1.8.1... 100%
Progress: Downloading KB2919355 1.0.20160915... 100%
Progress: Downloading KB2919442 1.0.20160915... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.4... 100%
Progress: Downloading dotnetfx 4.8.0.20190930... 100%
Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%
Progress: Downloading visualstudio-installer 2.0.1... 100%
Progress: Downloading php 8.0.0... 100%
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%

chocolatey-visualstudio.extension v1.8.1 [Approved]
chocolatey-visualstudio.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-visualstudio extensions.
 The install of chocolatey-visualstudio.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-visualstudio'

KB2919442 v1.0.20160915 [Approved]
kb2919442 package files install completed. Performing other installation steps.
The package KB2919442 wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919442 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB2919355 v1.0.20160915 [Approved]
kb2919355 package files install completed. Performing other installation steps.
Skipping installation because this hotfix only applies to Windows 8.1 and Windows Server 2012 R2.
 The install of kb2919355 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

chocolatey-windowsupdate.extension v1.0.4 [Approved]
chocolatey-windowsupdate.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-windowsupdate extensions.
 The install of chocolatey-windowsupdate.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-windowsupdate'

KB2999226 v1.0.20181019 [Approved] - Possibly broken
kb2999226 package files install completed. Performing other installation steps.
Skipping installation because update KB2999226 does not apply to this operating system (Microsoft).
 The install of kb2999226 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

chocolatey-dotnetfx.extension v1.0.1 [Approved]
chocolatey-dotnetfx.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-dotnetfx extensions.
 The install of chocolatey-dotnetfx.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-dotnetfx'

dotnetfx v4.8.0.20190930 [Approved]
dotnetfx package files install completed. Performing other installation steps.
Downloading dotnetfx 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/014120d7-d689-4305-befd-3cb711108212/0fd66638cde16859462
a6243a4629a50/ndp48-x86-x64-allos-enu.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\dotnetfx\4.8.0.2019
0930\ndp48-x86-x64-allos-enu.exe (111.94 MB).
Download of ndp48-x86-x64-allos-enu.exe (111.94 MB) completed.
Hashes match.
Installing dotnetfx...
WARNING: Microsoft .NET Framework 4.8 has been installed, but a reboot is required to finalize the installation. Until t
he computer is rebooted, dependent packages may fail to install or function properly.
 The install of dotnetfx was successful.
  Software installed as 'exe', install location is likely default.

visualstudio-installer v2.0.1 [Approved]
visualstudio-installer package files install completed. Performing other installation steps.
 The install of visualstudio-installer was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

visualstudio2019buildtools v16.8.2.0 [Approved]
visualstudio2019buildtools package files install completed. Performing other installation steps.
Downloading channel manifest
  from 'https://aka.ms/vs/16/release/channel'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocolatey-visualst
udio.extension\ChannelManifest_-602808024.man (128.8 KB).
Download of ChannelManifest_-602808024.man (128.8 KB) completed.
Downloading catalog manifest
  from 'https://download.visualstudio.microsoft.com/download/pr/9d2147aa-7b01-4336-b665-8fe07735e5ee/c7464474134c0a53c3d
c7d66ce09bd7f00df721146e8578ab6961a75fcf21194/VisualStudio.vsman'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\chocolatey-visualst
udio.extension\Catalog_-1751506352.man (9.65 MB).
Download of Catalog_-1751506352.man (9.65 MB) completed.
Downloading visualstudio2019buildtools
  from 'https://download.visualstudio.microsoft.com/download/pr/9d2147aa-7b01-4336-b665-8fe07735e5ee/c4b2212532e637ae357
83660e79211e0604d0b61e54f6c7db69df30ce446bd73/vs_BuildTools.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\visualstudio2019bui
ldtools\16.8.2.0\vs_BuildTools.exe (1.34 MB).
Download of vs_BuildTools.exe (1.34 MB) completed.
Hashes match.
Installing visualstudio2019buildtools...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1028\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\2052\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1029\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1031\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1046\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1042\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1036\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\3082\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1040\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1045\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1041\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1055\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1049\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\HelpFi
le\1033\help.html...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\vs_set
up_bootstrapper.exe...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.Diagnostics.Tracing.EventSource.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.RemoteControl.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.Setup.Common.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.Setup.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.Setup.Download.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.Telemetry.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Micros
oft.VisualStudio.Utilities.Internal.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\Newton
soft.Json.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\zh-Han
t\vs_setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\fr\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\tr\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\it\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\pl\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\ko\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\ja\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\zh-Han
s\vs_setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\cs\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\pt-BR\
vs_setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\ru\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\es\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\de\vs_
setup_bootstrapper.resources.dll...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\vs_set
up_bootstrapper.config...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\vs_set
up_bootstrapper.exe.config...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\detect
ion.json...

Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\9187fec000c0c3881c17\vs_bootstrapper_d15\vs_set
up_bootstrapper.json...

visualstudio2019buildtools has been installed.
  visualstudio2019buildtools may be able to be automatically uninstalled.
 The install of visualstudio2019buildtools was successful.
  Software installed to '"C:\Program Files (x86)\Microsoft Visual Studio\Installer"'

chocolatey-core.extension v1.3.5.1 [Approved]
chocolatey-core.extension package files install completed. Performing other installation steps.
 Installed/updated chocolatey-core extensions.
 The install of chocolatey-core.extension was successful.
  Software installed to 'C:\ProgramData\chocolatey\extensions\chocolatey-core'

php v8.0.0 [Approved]
php package files install completed. Performing other installation steps.
(0) : Required file 'alink.dll' could not be found

(1) : using System;

WARNING: Failure attempting to let Explorer know about updated environment settings.
  Cannot add type. Compilation errors occurred.
Extracting 64-bit C:\ProgramData\chocolatey\lib\php\tools\php-8.0.0-nts-Win32-vs16-x64.zip to C:\tools\php80...
C:\tools\php80
PATH environment variable does not have C:\tools\php80 in it. Adding...
(0) : Required file 'alink.dll' could not be found

(1) : using System;

WARNING: Failure attempting to let Explorer know about updated environment settings.
  Cannot add type. Compilation errors occurred.
Creating default php.ini
Configuring PHP extensions directory
Please make sure you have CGI installed in IIS for local hosting
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of php was successful.
  Software installed to 'C:\tools\php80'

Chocolatey installed 11/11 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - kb2919355 v1.0.20160915
 - chocolatey-core.extension v1.3.5.1
 - kb2999226 v1.0.20181019
 - dotnetfx v4.8.0.20190930
 - chocolatey-visualstudio.extension v1.8.1
 - visualstudio2019buildtools v16.8.2.0
 - kb2919442 v1.0.20160915
 - php v8.0.0
 - visualstudio-installer v2.0.1
 - chocolatey-dotnetfx.extension v1.0.1
 - chocolatey-windowsupdate.extension v1.0.4

Packages requiring reboot:
 - dotnetfx (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.

C:\>cd C:\tools\php8.0

C:\tools\php80>dir
 Volume in drive C has no label.
 Volume Serial Number is B087-E40A

 Directory of C:\tools\php80

12/03/2020  11:30 AM    <DIR>          .
12/03/2020  11:30 AM    <DIR>          ..
11/25/2020  03:01 AM           120,320 deplister.exe
11/25/2020  03:01 AM    <DIR>          dev
11/25/2020  03:01 AM    <DIR>          ext
11/25/2020  03:13 AM    <DIR>          extras
11/25/2020  03:01 AM         1,419,264 glib-2.dll
11/25/2020  03:01 AM            18,432 gmodule-2.dll
11/25/2020  03:01 AM        28,568,064 icudt68.dll
11/25/2020  03:01 AM         2,962,944 icuin68.dll
11/25/2020  03:01 AM            60,416 icuio68.dll
11/25/2020  03:01 AM         2,187,264 icuuc68.dll
11/25/2020  03:01 AM    <DIR>          lib
11/25/2020  03:01 AM         3,467,264 libcrypto-1_1-x64.dll
11/25/2020  03:01 AM            42,496 libenchant2.dll
11/25/2020  03:01 AM           282,112 libpq.dll
11/25/2020  03:01 AM           194,560 libsasl.dll
11/25/2020  03:01 AM           303,616 libsodium.dll
11/25/2020  03:01 AM         1,598,464 libsqlite3.dll
11/25/2020  03:01 AM           281,600 libssh2.dll
11/25/2020  03:01 AM           685,568 libssl-1_1-x64.dll
11/25/2020  03:01 AM             3,272 license.txt
11/25/2020  03:01 AM            16,451 news.txt
11/25/2020  03:01 AM           206,336 nghttp2.dll
11/25/2020  03:13 AM                43 phar.phar.bat
11/25/2020  03:13 AM            65,237 pharcommand.phar
11/25/2020  03:01 AM            70,144 php-cgi.exe
11/25/2020  03:01 AM            38,400 php-win.exe
11/25/2020  03:01 AM           139,776 php.exe
12/03/2020  11:30 AM            74,406 php.ini
11/25/2020  03:01 AM            74,259 php.ini-development
11/25/2020  03:01 AM            74,407 php.ini-production
11/25/2020  03:01 AM         8,875,520 php8.dll
11/25/2020  03:01 AM           893,072 php8embed.lib
11/25/2020  03:01 AM           302,080 php8phpdbg.dll
11/25/2020  03:01 AM           304,640 phpdbg.exe
11/25/2020  03:01 AM            29,167 readme-redist-bins.txt
11/25/2020  03:01 AM             5,370 README.md
11/25/2020  03:01 AM             2,311 snapshot.txt
              33 File(s)     53,367,275 bytes
               6 Dir(s)  19,920,891,904 bytes free

C:\tools\php80>php -v

C:\tools\php80>php -v

C:\tools\php80>php-win -v

C:\tools\php80>choco install vcredist140
Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

Installing the following packages:
vcredist140
By installing you accept licenses for the packages.
Progress: Downloading vcredist140 14.28.29325.2... 100%
Progress: Downloading KB3033929 1.0.5... 100%
Progress: Downloading KB3035131 1.0.3... 100%

KB3035131 v1.0.3 [Approved]
kb3035131 package files install completed. Performing other installation steps.
The package KB3035131 wants to run 'ChocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): A

Skipping installation because update KB3035131 does not apply to this operating system (Microsoft).
 The install of kb3035131 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

KB3033929 v1.0.5 [Approved]
kb3033929 package files install completed. Performing other installation steps.
Skipping installation because update KB3033929 does not apply to this operating system (Microsoft).
 The install of kb3033929 was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

vcredist140 v14.28.29325.2 [Approved]
vcredist140 package files install completed. Performing other installation steps.
Downloading vcredist140-x86
  from 'https://download.visualstudio.microsoft.com/download/pr/8ecb9800-52fd-432d-83ee-d6e037e96cc2/50A3E92ADE4C2D8F310
A2812D46322459104039B9DEADBD7FDD483B5C697C0C8/VC_redist.x86.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist140\14.28.2
9325.2\VC_redist.x86.exe (13.67 MB).
Download of VC_redist.x86.exe (13.67 MB) completed.
Hashes match.
Installing vcredist140-x86...
vcredist140-x86 has been installed.
Downloading vcredist140-x64 64 bit
  from 'https://download.visualstudio.microsoft.com/download/pr/89a3b9df-4a09-492e-8474-8f92c115c51d/B1A32C71A6B7D597890
4FB223763263EA5A7EB23B2C44A0D60E90D234AD99178/VC_redist.x64.exe'
Progress: 100% - Completed download of C:\Users\ContainerAdministrator\AppData\Local\Temp\chocolatey\vcredist140\14.28.2
9325.2\VC_redist.x64.exe (14.2 MB).
Download of VC_redist.x64.exe (14.2 MB) completed.
Hashes match.
Installing vcredist140-x64...
vcredist140-x64 has been installed.
  vcredist140 may be able to be automatically uninstalled.
 The install of vcredist140 was successful.
  Software installed as 'exe', install location is likely default.

Chocolatey installed 3/3 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

C:\tools\php80>php -v
PHP 8.0.0 (cli) (built: Nov 24 2020 22:02:58) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
```

</p>
</details>

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [X] My code follows the code style of this repository.
- [X] My change requires a change to documentation (this usually means the notes in the description of a package).
- [X] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [X] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [X] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by shivammathur** [comment]
@majkinetor Please review this PR

**Comment by shivammathur** [comment]
@majkinetor Thanks

**Comment by al-cheb** [comment]
Hello, @majkinetor 
Could you please provide ETA when the package will be available via choco?

**Comment by gep13** [comment]
@majkinetor thanks for merging this!  Can we also push out a new package fix notation version of the package?  What is the correct process for doing this?

**Comment by majkinetor** [comment]
Just do empty commit with `[AU package-name]`. Version must not use build number.

**Comment by gep13** [comment]
@majkinetor thank you for confirming.  @mkevenaar has just done that, and a new package version with the fix notation has been pushed.

**Comment by mkevenaar** [comment]
I just did that here: https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/80ae049dbfda9775a8eeedfdbdc40abe2d5b1a0a

**Comment by gep13** [comment]
@majkinetor this was only for a single stream, so he used a slightly different commit message, but the end result seems to be what is desired.

**Comment by mkevenaar** [comment]
New package is pushed and waiting moderation: https://chocolatey.org/packages/php/8.0.0.20201221

**Pull request merged**
