### PR TITLE
(spotify) Installer name updated

### PR DESCRIPTION
**Pull request by tipek360**
Changed standard installer to full installer.

[Spotify] changed installer

## Description
Changed installer to full installer so it downloads from this address https://download.spotify.com/SpotifyFullSetup.exe

## Motivation and Context
Spotify was not installing at all using chocolatey

## How Has this Been Tested?
I wanted to install spotify but installation stuck on "SUCCESS: The scheduled task "spotify" was successfully deleted."

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [ ] The changes only affect a single package (not including meta package).

## Original Location
- [Original Repository](https://github.com/chocolatey-community/chocolatey-coreteampackages/tree/master/automatic/spotify)
- [Open Issues](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues?q=is%3Aissue+is%3Aopen+spotify)
  - [x] [Issue](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1620)
- [x] *Include the link to the opened PR that removes the package from the original location*
- [x] The [migration guidelines](https://github.com/chocolatey-community/chocolatey-coreteampackages/wiki/Package-migration-process) have been followed

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Thank you for opening this pull request, unfortunately as it stands we can not accept this pull request.

You need to make the necessary changes to the `update.ps1` script in the package folder.
This script automatically populates the install script with both the URL and the hashes.

**Comment by tipek360** [comment]
OK hopefully I fixed it in patch-1 branch in my fork

**Comment by AdmiringWorm** [comment]
Hmm, I had to dig around a bit due to remembering something from the past.

It seems like we used to use the full installer at some point (back in 2019), but due to the installer hash (and version) not being the same for every location, we changed it do use the Online installer instead (the one currently in use).

> I wanted to install spotify but installation stuck on "SUCCESS: The scheduled task "spotify" was successfully deleted."

There is nothing more outputted by the package itself, unfortunately due to the nature of trying to install Spotify in a scheduled task (or just install it at all), there are a number of ways that prevents the installation.

Typically, everything I have seen in the past points to something user environment-related.
It could be due to the Windows Store edition already being installed, or something else (like an anti-virus) preventing the installation.

We could always try changing back to the full installer, but unfortunately, I have my doubts it will make any change to the current approach.

Reference from the commit regarding changing away from the full installer: https://github.com/chocolatey-community/chocolatey-coreteampackages/commit/8935ea2cc9dde18b4e306e77b21ac642f255d2d9#diff-9e1944b3df6ad673b36fbcbf3366589d056b5f8ef0d15fd3689a6adab539e808

**Comment by pauby** [comment]
@tipek360 are you in a position to resolve the issues with this?

**Comment by tipek360** [comment]
@pauby I tried to resolve it but it looks that this probably would be much more complicated error than I expected.

**Comment by pauby** [comment]
Thanks @tipek360. I'll go ahead and close this.

**Pull request closed without merging**
