### PR TITLE
(avidemux) Update update.ps1

### PR DESCRIPTION
**Pull request by Hattshire**
to support unmatched releases

## Motivation and Context
#1480 

## How Has this Been Tested?

Raw PS-tested/Not tested

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [ ] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [ ] All files are up to date with the latest [Contributing Guidelines](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

### CODE REVIEW

**Comment by gep13** [comment]
@Hattshire thanks for taking the time to do this.  Were you also able to look at the additional requirement regarding the silent arguments required to make the installation work unattended?

**Comment by Hattshire** [comment]
> 
> 
> @Hattshire thanks for taking the time to do this. Were you also able to look at the additional requirement regarding the silent arguments required to make the installation work unattended?

The installer is based on QT installer framework, which only have silent updates, not installations. An automation script can be given apparently.

**Comment by Hattshire** [comment]
nvm, chocolateyInstall.ps1:l16, @AdmiringWorm wrote the solution 9 months ago but used `Get-OSArchitectureWidth`, which is not supported on some PS versions, at least on mine it's not.

**Comment by Hattshire** [comment]
Also note that the PS AppVeyor uses apparently has `Get-OSArchitectureWidth` implemented, see https://ci.appveyor.com/project/chocolateycommunity/chocolatey-coreteampackages/builds/33211071#L257

**Comment by AdmiringWorm** [comment]
@Hattshire `Get-OSArchitectureWidth` is a chocolatey helper, not a built-in PowerShell function.

So please revert back to using that again.

https://chocolatey.org/docs/helpers-get-osarchitecture-width

**Comment by Hattshire** [comment]
Upgrading from 2.7.1 needs prior uninstall, should be called `chocolateyUninstall.ps1` from `chocolateyInstall.ps1`?

**Comment by majkinetor** [comment]
Yes you can do that.

I think your current updater will mix x32 and x64 bit versions. Maybe its better to just use x64 from now on ?

**Comment by Hattshire** [comment]
> I think your current updater will mix x32 and x64 bit versions. 

The latest of the two, as the developer is releasing per-architecture fixes, I think there's a probability that it could happen again. However I believe that the dev will publish both newer versions as `.6` instead of x32 `.5` and x64 `.6`

> Maybe its better to just use x64 from now on ?

I think so, but there's x32 support upstream. Someone using choco will use it? idk

**Comment by majkinetor** [comment]
> The latest of the two, as the developer is releasing per-architecture fixes, I think there's a probability that it could happen again. However I believe that the dev will publish both newer versions as .6 instead of x32 .5 and x64 .6

So what is going to happen when 1 ver has x32 and other x64 ?

**Comment by Hattshire** [comment]
> 
> 
> > The latest of the two, as the developer is releasing per-architecture fixes, I think there's a probability that it could happen again. However I believe that the dev will publish both newer versions as .6 instead of x32 .5 and x64 .6
> 
> So what is going to happen when 1 ver has x32 and other x64 ?

Lets say the latest x32 version is 1.2.3 and the latest x64 is 1.2.4:
 - Package version: 1.2.4 -> CHOCOPKG-v1.2.4.nupkg
 - x32 binary version: 1.2.3 -> Install-x32-v1.2.3.exe
 - x64 binary version: 1.2.4 -> Install-x64-v1.2.4.exe

In the other way around if the latest versions are 5.6.7 for x32 and 5.6.6 for x64:
 - Package version: 5.6.7 -> CHOCOPKG-v5.6.7.nupkg
 - x32 binary version: 5.6.7 -> Setup32-v567.exe
 - x64 binary version: 5.6.6 -> Setup64-v566.exe

That's how I see it, however, I have no problem whatsoever changing it to x64-only releases, it would be easier and cleaner than this sketchy way of providing symmetrical-to-upstream releases.

**Comment by majkinetor** [comment]
Exactly. Its not correct by any definition and road we never took so far (although this is not the first case). I suggest we should go with x64 only version. Its video tool too, it should be used with x64 arch.

Perhaps this deserves an extra note, that since versino x.y.z. package is only x64 bit due to the upstream "problems".

**Comment by majkinetor** [comment]
Thx @Hattshire for making this work again.

**Pull request merged**
